version: '3'
services:
  attendance-api:
    image: attendance-api:latest
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - "3000:3000"
    build: .
    links:
    - attendance-postgres:db
  attendance-postgres:
     image: attendance-postgres:latest
     ports:
     - "5432:5432"
